[package]
name = "collections"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }

ahash = "0.8.11"
slab = "0.4.9"
hashbrown = { version = "0.14.3", features = ["raw"] }
serde = { version = "1.0.203" }
